version: '3.3'
services:
  api:
    build: .
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:9.6.5
    # Provide a location for data to be saved will persist data
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: