# Generated by Django 2.0 on 2018-09-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('diameter', models.FloatField()),
                ('distance_from_sun', models.FloatField()),
                ('number_of_moons', models.IntegerField()),
            ],
        ),
    ]
